import "./globals.css";

import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { cn } from "@workspace/ui/lib/utils";
import { notFound } from "next/navigation";
import { Header, Footer } from "@workspace/ui/components/layout";
import { getGlobalPageData } from "@/data/loaders";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontHeading = Nunito({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getGlobalPageData();
  if (!data) notFound();

  const { topNav, footer } = data.data;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-sans antialiased flex flex-col items-center justify-center min-h-screen",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header data={topNav} />
          {children}
          <Footer data={footer} />
        </ThemeProvider>
      </body>
    </html>
  );
}
